In [3]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [4]:
import duckdb
conn=duckdb.connect()
df = pd.read_csv('corona_tested_006.csv')

<ipython-input-4-e739dc52c32b>:3: DtypeWarning: Columns (4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('corona_tested_006.csv')

In [5]:
conn.register("df",df)

In [6]:
conn.execute("select * from df").fetchdf()

,Ind_ID,Test_date,Cough_symptoms,Fever,Sore_throat,Shortness_of_breath,Headache,Corona,Age_60_above,Sex,Known_contact
0,1,11-03-2020,TRUE,FALSE,TRUE,FALSE,FALSE,negative,None,None,Abroad
1,2,11-03-2020,FALSE,TRUE,FALSE,FALSE,FALSE,positive,None,None,Abroad
2,3,11-03-2020,FALSE,TRUE,FALSE,FALSE,FALSE,positive,None,None,Abroad
3,4,11-03-2020,TRUE,FALSE,FALSE,FALSE,FALSE,negative,None,None,Abroad
4,5,11-03-2020,TRUE,FALSE,FALSE,FALSE,FALSE,negative,None,None,Contact with confirmed
...,...,...,...,...,...,...,...,...,...,...,...
185683,185684,18-04-2020,True,False,False,False,False,negative,None,female,Abroad
185684,185685,18-04-2020,False,False,False,False,False,negative,None,female,Other
185685,185686,18-04-2020,True,False,False,False,False,negative,None,male,Abroad
185686,185687,18-04-2020,True,False,False,False,False,negative,None,female,Other
185687,1,None,None,None,None,None,None,None,None,None,None

In [ ]:
#1 Find the number of COVID patients who faced shortness of breath:

conn.execute("SELECT COUNT(*) AS NumPatientsWithShortnessOfBreath FROM df WHERE Corona = 'positive' AND Shortness_of_breath = true;").fetchdf()

In [ ]:
# 2. Find the number of negative COVID patients with fever and sore throat:

conn.execute("SELECT COUNT(*) AS NumNegativePatientsWithFeverAndSoreThroat FROM df where Corona = 'negative' AND Fever = true AND Sore_throat = true; ").fetchdf()

In [ ]:
# 3.Group the data by month and rank the number of positive cases:

conn.execute("SELECT MONTH(Test_date) AS Month, COUNT(*) AS NumPositiveCases FROM df WHERE Corona = 'positive' GROUP BY Month ORDER BY NumPositiveCases DESC;").fetchdf()

In [ ]:
# 4. Identify female negative COVID patients with cough and headache:

conn.execute("SELECT COUNT(*) AS NumFemaleNegativePatientsWithCoughAndHeadache FROM df WHERE Corona = 'negative' AND Sex = 'female' AND Cough_symptoms = true AND Headache = true;").fetchdf()

In [ ]:
# 5 Determine how many elderly COVID patients faced breathing problems:

conn.execute("SELECT COUNT(*) AS NumElderlyPatientsWithBreathingProblems FROM df WHERE corona = 'positive' AND Age_60_above = true AND Shortness_of_breath = true;").fetchdf()

In [ ]:
# 6 Identify the three most common symptoms among COVID-positive patients:

conn.execute("SELECT COUNT(*) AS SymptomCount, 'Cough_symptoms' AS Symptom FROM df WHERE Corona = 'positive' AND Cough_symptoms = trueUNION SELECT COUNT(*) AS SymptomCount, 'Fever' AS Symptom FROM df WHERE Corona = 'positive' AND Fever = true UNION SELECT COUNT(*) AS SymptomCount, 'Sore_throat' AS Symptom FROM df WHERE Corona = 'positive' AND Sore_throat = true ORDER BY SymptomCount DESC LIMIT 3; ").fetchdf()

In [ ]:
# 7 Identify the least common symptom among COVID-negative individuals:

conn.execute("SELECT COUNT(*) AS SymptomCount, 'Shortness_of_breath' AS Symptom FROM df WHERE Corona = 'negative' AND Shortness_of_breath = true UNION SELECT COUNT(*) AS SymptomCount, 'Headache' AS Symptom FROM df WHERE Corona = 'negative' AND Headache = true ORDER BY SymptomCount LIMIT 1; ").fetchdf()